### ISSUE TITLE
Version detection breaks on a comment

### ISSUE THREAD

**Issue by laughedelic** [AvaPL/scalafmt-native-formatter#12]
I have a config file like this: 

```hocon
# Scalafmt version should be set explicitly because defaults change over time
version = 2.7.5

...
```

So the first is treated as a version, since it contains `version` word.

I think it's a regression in 0.1.1.

**Comment by AvaPL** [comment]
Whoa, I did a serious spam here. Next time I'll use a tool like https://github.com/nektos/act instead of spamming commits just to test my solution, I'm still learning :) Anyway, the problem is now fixed. Thank you for contributing and using this action!
